# Generated by Django 5.2.6 on 2025-09-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=20)),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=10)),
                ('docente', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('obra_social', models.CharField(max_length=50)),
                ('control_oftam', models.CharField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('anio', models.IntegerField(default=2025)),
                ('av_od_lejos', models.CharField(blank=True, max_length=20, null=True, verbose_name='AV OD Lejos')),
                ('av_oi_lejos', models.CharField(blank=True, max_length=20, null=True, verbose_name='AV OI Lejos')),
                ('av_cerca_oa', models.CharField(blank=True, max_length=20, null=True, verbose_name='AV Cerca OA')),
                ('motilidad_cda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motilidad C-D-A')),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='usuarios.jardin')),
            ],
        ),
        migrations.CreateModel(
            name='Relevamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala_grado_seccion', models.CharField(max_length=50, verbose_name='Sala / Grado / Sección')),
                ('docente', models.CharField(max_length=100, verbose_name='Docente')),
                ('cantidad_estudiantes', models.PositiveIntegerField(default=0, verbose_name='Cantidad de estudiantes')),
                ('ya_evaluados', models.PositiveIntegerField(default=0, verbose_name='Ya evaluados')),
                ('autorizados', models.PositiveIntegerField(default=0, verbose_name='Autorizados')),
                ('ausentes', models.PositiveIntegerField(default=0, verbose_name='Ausentes')),
                ('no_colaboro', models.PositiveIntegerField(default=0, verbose_name='No colaboró')),
                ('grado_i', models.PositiveIntegerField(default=0, verbose_name='Grado I')),
                ('grado_ii', models.PositiveIntegerField(default=0, verbose_name='Grado II')),
                ('grado_iii', models.PositiveIntegerField(default=0, verbose_name='Grado III')),
                ('control_oftamologico_previo', models.BooleanField(default=False, verbose_name='Control oftalmológico previo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('anio', models.IntegerField(default=2025)),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevamientos', to='usuarios.jardin')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_nombre', models.CharField(max_length=100, verbose_name='Apellido y Nombre')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('turno', models.CharField(max_length=50, verbose_name='Turno')),
                ('grado_division', models.CharField(max_length=50, verbose_name='Grado/División')),
                ('fecha_turno', models.CharField(max_length=50, verbose_name='Fecha de turno')),
                ('centro_salud_prof', models.CharField(max_length=100, verbose_name='Centro de salud Prof.')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('anio', models.IntegerField(default=2025)),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.jardin')),
            ],
        ),
    ]
